# Generated by Django 5.0.6 on 2024-05-12 23:13

import assistant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=13, validators=[assistant.models.check_number])),
                ('email', models.EmailField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('FIN', 'Finance'), ('SALES', 'Sales')], max_length=50)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('analyst', 'Analyst'), ('assistant', 'Assistant')], max_length=50)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
